name: Demo

on:
  push:
    branches:
    - master
    paths:
    - '.github/workflows/ci.yml'
    - 'hello.txt'
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  hello:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Greeting
      run: |
        cat hello.txt
        echo github.ref = ${{ github.ref }}
        echo github.ref_name = ${{ github.ref_name }}
        echo github.ref_type = ${{ github.ref_type }}
        echo github.sha = ${{ github.sha }}
        echo github.action = ${{ github.action }}
        echo github.action_path = ${{ github.action_path }}
        echo github.actor = ${{ github.actor }}
        echo github.event_name = ${{ github.event_name }}

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker
      run: docker --version
