name: Demo

on:
  push:
    branches:
    - master
    paths:
    - '.github/workflows/**'
    - 'hello.txt'

jobs:
  hello:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Greeting
      run: cat hello.txt

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker
      run: docker --version
