name: git push example

on:
  push:
    paths:
    - '.github/workflows/git-push.yaml'
    - 'date-trigger.txt'
  workflow_dispatch: {}

jobs:
  git-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: date > date.txt
    - run: |
        git config --local user.email backpaper0@gmail.com
        git config --local user.name "Uragami Taichi"
    - run: |
        git add date.txt
        git stash
        git fetch --no-tags --depth=1 origin date
        git checkout date
        git rm -fr date.txt
        git commit -m "WIP"
        git stash pop
        git commit -m --amend "Update date.txt"
        git push origin date

