on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
        spring: [ 2.2, 2.3, 2.4, 2.5 ]
        doma: [ 2.49, 2.50 ]
    steps:
    - run: |
        echo ${{ matrix.java }} / ${{ matrix.spring }} / ${{ matrix.doma }}
