name: Java CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [1.8, 11]
    name: Test by Java ${{matrix.java}}
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - name: Build with Maven
      run: ./mvnw -B test
