on:
  push:
    branches:
      - master
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo github.action              = ${{ github.action }}
        echo github.action_path         = ${{ github.action_path }}
        echo github.action_ref          = ${{ github.action_ref }}
        echo github.action_repository   = ${{ github.action_repository }}
        echo github.action_status       = ${{ github.action_status }}
        echo github.actor               = ${{ github.actor }}
        echo github.actor_id            = ${{ github.actor_id }}
        echo github.base_ref            = ${{ github.base_ref }}
        echo github.event_name          = ${{ github.event_name }}
        echo github.event_path          = ${{ github.event_path }}
        echo github.head_ref            = ${{ github.head_ref }}
        echo github.job                 = ${{ github.job }}
        echo github.path                = ${{ github.path }}
        echo github.ref                 = ${{ github.ref }}
        echo github.ref_name            = ${{ github.ref_name }}
        echo github.ref_type            = ${{ github.ref_type }}
        echo github.repository          = ${{ github.repository }}
        echo github.repository_id       = ${{ github.repository_id }}
        echo github.repository_owner    = ${{ github.repository_owner }}
        echo github.repository_owner_id = ${{ github.repository_owner_id }}
        echo github.run_id              = ${{ github.run_id }}
        echo github.run_number          = ${{ github.run_number }}
        echo github.run_attempt         = ${{ github.run_attempt }}
        echo github.sha                 = ${{ github.sha }}
        echo github.triggering_actor    = ${{ github.triggering_actor }}

