name: Zip

on: [workflow_dispatch]

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get install -y convmv
        convmv --notest -r -f utf8 -t sjis ./zip-files
        cd zip-files
        zip -r ../example.zip .
    - uses: actions/upload-artifact@v3
      with:
        name: example.zip
        path: example.zip
        retention-days: 1

