name: Zip

on: [workflow_dispatch]

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get install -y convmv
        mv zip-files example
        convmv --notest -r -f utf8 -t sjis example
        zip -r example.zip example
    - uses: actions/upload-artifact@v3
      with:
        name: example
        path: example.zip
        retention-days: 1

